<?xml version="1.0" encoding="UTF-8"?>
<SceneSpec xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <Scene>
        <SkySpec>Sky.spec</SkySpec>
        <TerrainSpec>Terrain.spec</TerrainSpec>
        <PlayerSpec>
            <Spec>paladin_j_nordstrom.spec</Spec>
            <Position>
                <X>14.464228</X>
                <Y>0.60000002</Y>
                <Z>65.107788</Z>
            </Position>
            <Rotation>
                <X>0</X>
                <Y>0</Y>
                <Z>0</Z>
            </Rotation>
            <Scale>
                <X>3</X>
                <Y>3</Y>
                <Z>3</Z>
            </Scale>
        </PlayerSpec>
        <EnemySpecs>
            <EnemyCount>0</EnemyCount>
        </EnemySpecs>
        <ObjectSpecs>
            <ObjectCount>1</ObjectCount>
            <Object0>Scottish Sword.spec</Object0>
            <Position>
                <X>12.498181</X>
                <Y>4.9384208</Y>
                <Z>65.264511</Z>
            </Position>
            <Rotation>
                <X>0</X>
                <Y>0</Y>
                <Z>0</Z>
            </Rotation>
            <Scale>
                <X>3</X>
                <Y>3</Y>
                <Z>3</Z>
            </Scale>
        </ObjectSpecs>
    </Scene>
</SceneSpec>
