<?xml version="1.0" encoding="UTF-8"?>
<TerrainDesc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <Desc>
        <HeightMap>E:/D3DGame/_Textures/HeightMap/terrain(normal).raw</HeightMap>
        <HeightScale>50</HeightScale>
        <HeightMapWidth>2049</HeightMapWidth>
        <HeightMapHeight>2049</HeightMapHeight>
        <LayerMaps>
            <layer1>../../_Textures/Dirt2.png</layer1>
            <layer2>../../_Textures/stone.png</layer2>
            <layer3>../../_Textures/snow.png</layer3>
        </LayerMaps>
        <BlendHeight>
            <blendHeight1>0.059999999</blendHeight1>
            <blendHeight2>0.40000001</blendHeight2>
            <blendHeight3>0</blendHeight3>
            <blendHeight4>0.75</blendHeight4>
        </BlendHeight>
        <BlendUse>
            <UseBlend1>1</UseBlend1>
            <UseBlend2>1</UseBlend2>
            <UseBlend3>1</UseBlend3>
        </BlendUse>
        <DetailValue>0.99900001</DetailValue>
        <DetailIntensity>1</DetailIntensity>
        <AmbientColor>
            <AmbientR>1</AmbientR>
            <AmbientG>1</AmbientG>
            <AmbientB>1</AmbientB>
            <AmbientA>1</AmbientA>
        </AmbientColor>
        <TerrainDiffuse></TerrainDiffuse>
        <DiffuseColor>
            <DiffuseR>1</DiffuseR>
            <DiffuseG>1</DiffuseG>
            <DiffuseB>1</DiffuseB>
            <DiffuseA>1</DiffuseA>
        </DiffuseColor>
        <TerrainSpecular></TerrainSpecular>
        <SpecularColor>
            <SpecularR>0.89999998</SpecularR>
            <SpecularG>0.89999998</SpecularG>
            <SpecularB>0.89999998</SpecularB>
            <SpecularA>16</SpecularA>
        </SpecularColor>
        <SpecularIntensity>16</SpecularIntensity>
        <TerrainNormal></TerrainNormal>
        <TerrainDetail></TerrainDetail>
        <TexScale>32</TexScale>
        <FogStart>300</FogStart>
        <FogRange>200</FogRange>
    </Desc>
    <GrassDesc>
        <Wind>
            <WindX>0</WindX>
            <WindY>0</WindY>
        </Wind>
        <GrassCount>0</GrassCount>
    </GrassDesc>
    <FlowerDesc>
        <FlowerCount>9</FlowerCount>
        <Flower0>
            <TextureNumber>0</TextureNumber>
            <FlowerNum>5000</FlowerNum>
            <FlowerSize>200</FlowerSize>
            <NumOfRoots>5000</NumOfRoots>
            <FlowerPosition>
                <FlowerX>36.434387</FlowerX>
                <FlowerY>-1.0737418e+08</FlowerY>
                <FlowerZ>97.408752</FlowerZ>
            </FlowerPosition>
        </Flower0>
        <Flower1>
            <TextureNumber>0</TextureNumber>
            <FlowerNum>5000</FlowerNum>
            <FlowerSize>200</FlowerSize>
            <NumOfRoots>5000</NumOfRoots>
            <FlowerPosition>
                <FlowerX>36.566467</FlowerX>
                <FlowerY>-1.0737418e+08</FlowerY>
                <FlowerZ>97.154541</FlowerZ>
            </FlowerPosition>
        </Flower1>
        <Flower2>
            <TextureNumber>0</TextureNumber>
            <FlowerNum>5000</FlowerNum>
            <FlowerSize>200</FlowerSize>
            <NumOfRoots>5000</NumOfRoots>
            <FlowerPosition>
                <FlowerX>36.566467</FlowerX>
                <FlowerY>-1.0737418e+08</FlowerY>
                <FlowerZ>97.154541</FlowerZ>
            </FlowerPosition>
        </Flower2>
        <Flower3>
            <TextureNumber>0</TextureNumber>
            <FlowerNum>5000</FlowerNum>
            <FlowerSize>200</FlowerSize>
            <NumOfRoots>5000</NumOfRoots>
            <FlowerPosition>
                <FlowerX>36.562927</FlowerX>
                <FlowerY>-1.0737418e+08</FlowerY>
                <FlowerZ>96.49292</FlowerZ>
            </FlowerPosition>
        </Flower3>
        <Flower4>
            <TextureNumber>0</TextureNumber>
            <FlowerNum>5000</FlowerNum>
            <FlowerSize>200</FlowerSize>
            <NumOfRoots>5000</NumOfRoots>
            <FlowerPosition>
                <FlowerX>36.562927</FlowerX>
                <FlowerY>-1.0737418e+08</FlowerY>
                <FlowerZ>96.49292</FlowerZ>
            </FlowerPosition>
        </Flower4>
        <Flower5>
            <TextureNumber>0</TextureNumber>
            <FlowerNum>5000</FlowerNum>
            <FlowerSize>200</FlowerSize>
            <NumOfRoots>5000</NumOfRoots>
            <FlowerPosition>
                <FlowerX>36.562927</FlowerX>
                <FlowerY>-1.0737418e+08</FlowerY>
                <FlowerZ>96.49292</FlowerZ>
            </FlowerPosition>
        </Flower5>
        <Flower6>
            <TextureNumber>0</TextureNumber>
            <FlowerNum>5000</FlowerNum>
            <FlowerSize>200</FlowerSize>
            <NumOfRoots>5000</NumOfRoots>
            <FlowerPosition>
                <FlowerX>36.562927</FlowerX>
                <FlowerY>-1.0737418e+08</FlowerY>
                <FlowerZ>96.49292</FlowerZ>
            </FlowerPosition>
        </Flower6>
        <Flower7>
            <TextureNumber>1</TextureNumber>
            <FlowerNum>5000</FlowerNum>
            <FlowerSize>200</FlowerSize>
            <NumOfRoots>5000</NumOfRoots>
            <FlowerPosition>
                <FlowerX>35.934814</FlowerX>
                <FlowerY>-1.0737418e+08</FlowerY>
                <FlowerZ>96.20575</FlowerZ>
            </FlowerPosition>
        </Flower7>
        <Flower8>
            <TextureNumber>2</TextureNumber>
            <FlowerNum>5000</FlowerNum>
            <FlowerSize>200</FlowerSize>
            <NumOfRoots>5000</NumOfRoots>
            <FlowerPosition>
                <FlowerX>39.083008</FlowerX>
                <FlowerY>-1.0737418e+08</FlowerY>
                <FlowerZ>98.813477</FlowerZ>
            </FlowerPosition>
        </Flower8>
    </FlowerDesc>
    <BillboardDesc>
        <BillboardCount>3</BillboardCount>
        <Billboard0>
            <BillboardType>1</BillboardType>
            <TextureNum>0</TextureNum>
            <BillSize>
                <X>10</X>
                <Y>10</Y>
            </BillSize>
            <BillPosition>
                <X>0.23181152</X>
                <Y>5.1960783</Y>
                <Z>162.94312</Z>
            </BillPosition>
        </Billboard0>
        <Billboard1>
            <BillboardType>1</BillboardType>
            <TextureNum>1</TextureNum>
            <BillSize>
                <X>31.333</X>
                <Y>35.588001</Y>
            </BillSize>
            <BillPosition>
                <X>31.754761</X>
                <Y>18.348934</Y>
                <Z>163.46436</Z>
            </BillPosition>
        </Billboard1>
        <Billboard2>
            <BillboardType>1</BillboardType>
            <TextureNum>3</TextureNum>
            <BillSize>
                <X>31.333</X>
                <Y>35.588001</Y>
            </BillSize>
            <BillPosition>
                <X>-15.532745</X>
                <Y>17.99008</Y>
                <Z>146.4303</Z>
            </BillPosition>
        </Billboard2>
    </BillboardDesc>
</TerrainDesc>
