<?xml version="1.0" encoding="UTF-8"?>
<GameCharacterSpec xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <ModelType>1</ModelType>
    <Name>MountainRocks01_A</Name>
    <Tag></Tag>
    <Colliders>
        <ColliderCount>0</ColliderCount>
    </Colliders>
    <IsChild>0</IsChild>
    <ParentBoneIndex>-1</ParentBoneIndex>
    <ParentName></ParentName>
    <Position>
        <X>0</X>
        <Y>0</Y>
        <Z>0</Z>
    </Position>
    <Rotation>
        <X>0</X>
        <Y>0</Y>
        <Z>0</Z>
    </Rotation>
    <Scale>
        <X>1</X>
        <Y>1</Y>
        <Z>1</Z>
    </Scale>
    <ClipNames>
        <ClipCount>0</ClipCount>
    </ClipNames>
    <FilePath>MountainRocks01_A</FilePath>
    <BTName></BTName>
    <BehaviourTree/>
</GameCharacterSpec>
