<?xml version="1.0" encoding="UTF-8"?>
<GameCharacterSpec xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <ModelType>2</ModelType>
    <Name>paladin_j_nordstrom</Name>
    <Tag>Player</Tag>
    <Colliders>
        <ColliderCount>0</ColliderCount>
    </Colliders>
    <IsChild>0</IsChild>
    <ParentBoneIndex>-1</ParentBoneIndex>
    <ParentName></ParentName>
    <Position>
        <X>0</X>
        <Y>0</Y>
        <Z>0</Z>
    </Position>
    <Rotation>
        <X>0</X>
        <Y>0</Y>
        <Z>0</Z>
    </Rotation>
    <Scale>
        <X>1</X>
        <Y>1</Y>
        <Z>1</Z>
    </Scale>
    <ClipNames>
        <ClipCount>10</ClipCount>
        <ClipName>Idle</ClipName>
        <ClipName>Walk</ClipName>
        <ClipName>Run</ClipName>
        <ClipName>Walk_Back</ClipName>
        <ClipName>Walk_Left</ClipName>
        <ClipName>Walk_Right</ClipName>
        <ClipName>Idle_Alart</ClipName>
        <ClipName>Idle2</ClipName>
        <ClipName>Attack1</ClipName>
        <ClipName>Attack2</ClipName>
    </ClipNames>
    <FilePath>paladin_j_nordstrom</FilePath>
    <BTName>Player 1</BTName>
    <BehaviourTree>
        <Decorator>Root</Decorator>
        <ChildCount>1</ChildCount>
        <Child>
            <Type>Selector</Type>
            <Name>Selector</Name>
        </Child>
        <Selector>Selector</Selector>
        <ChildCount>3</ChildCount>
        <Child>
            <Type>Task</Type>
            <Name>ActionAttack1</Name>
            <Type>Task</Type>
            <Name>ActionMove</Name>
            <Type>Sequence</Type>
            <Name>Sequence</Name>
        </Child>
        <Task>ActionAttack1</Task>
        <ChildCount>0</ChildCount>
        <Child/>
        <Task>ActionMove</Task>
        <ChildCount>0</ChildCount>
        <Child/>
        <Sequence>Sequence</Sequence>
        <ChildCount>3</ChildCount>
        <Child>
            <Type>Task</Type>
            <Name>ActionIdle</Name>
            <Type>Condition</Type>
            <Name>NumericRandom</Name>
            <Value>1</Value>
            <CompareType>2</CompareType>
            <Type>Task</Type>
            <Name>ActionIdle2</Name>
        </Child>
        <Task>ActionIdle</Task>
        <ChildCount>0</ChildCount>
        <Child/>
        <Condition>NumericRandom</Condition>
        <ChildCount>0</ChildCount>
        <Child/>
        <Task>ActionIdle2</Task>
        <ChildCount>0</ChildCount>
        <Child/>
    </BehaviourTree>
</GameCharacterSpec>
