<?xml version="1.0" encoding="UTF-8"?>
<TerrainDesc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <Desc>
        <HeightMap>E:/D3DGame/_Textures/HeightMap/MyTerrain.raw</HeightMap>
        <HeightScale>50</HeightScale>
        <HeightMapWidth>2049</HeightMapWidth>
        <HeightMapHeight>2049</HeightMapHeight>
        <LayerMaps>
            <layer1>E:/D3DGame/_Textures/stone.png</layer1>
            <layer2>E:/D3DGame/_Textures/Rocks.bmp</layer2>
            <layer3>E:/D3DGame/_Textures/darkdirt.png</layer3>
        </LayerMaps>
        <BlendHeight>
            <blendHeight1>0.235</blendHeight1>
            <blendHeight2>0.91799998</blendHeight2>
            <blendHeight3>0.016000001</blendHeight3>
            <blendHeight4>0.75</blendHeight4>
        </BlendHeight>
        <BlendUse>
            <UseBlend1>1</UseBlend1>
            <UseBlend2>1</UseBlend2>
            <UseBlend3>1</UseBlend3>
        </BlendUse>
        <DetailValue>0.99879998</DetailValue>
        <DetailIntensity>1</DetailIntensity>
        <AmbientColor>
            <AmbientR>1</AmbientR>
            <AmbientG>1</AmbientG>
            <AmbientB>1</AmbientB>
            <AmbientA>1</AmbientA>
        </AmbientColor>
        <TerrainDiffuse>E:/D3DGame/_Textures/Box_03.png</TerrainDiffuse>
        <DiffuseColor>
            <DiffuseR>1</DiffuseR>
            <DiffuseG>1</DiffuseG>
            <DiffuseB>1</DiffuseB>
            <DiffuseA>1</DiffuseA>
        </DiffuseColor>
        <TerrainSpecular></TerrainSpecular>
        <SpecularColor>
            <SpecularR>0.89999998</SpecularR>
            <SpecularG>0.89999998</SpecularG>
            <SpecularB>0.89999998</SpecularB>
            <SpecularA>16</SpecularA>
        </SpecularColor>
        <SpecularIntensity>16</SpecularIntensity>
        <TerrainNormal></TerrainNormal>
        <TerrainDetail></TerrainDetail>
        <TexScale>128</TexScale>
        <FogStart>300</FogStart>
        <FogRange>200</FogRange>
    </Desc>
    <GrassDesc>
        <Wind>
            <WindX>1</WindX>
            <WindY>0</WindY>
        </Wind>
        <GrassCount>0</GrassCount>
    </GrassDesc>
    <BillboardDesc>
        <BillboardCount>84</BillboardCount>
        <Billboard0>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-49.181732</X>
                <Y>42.380955</Y>
                <Z>-165.58252</Z>
            </BillPosition>
        </Billboard0>
        <Billboard1>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-139.64008</X>
                <Y>26.17647</Y>
                <Z>-408.46875</Z>
            </BillPosition>
        </Billboard1>
        <Billboard2>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-194.2197</X>
                <Y>29.386017</Y>
                <Z>-460.29761</Z>
            </BillPosition>
        </Billboard2>
        <Billboard3>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-163.93295</X>
                <Y>54.282974</Y>
                <Z>-310.67731</Z>
            </BillPosition>
        </Billboard3>
        <Billboard4>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-175.21994</X>
                <Y>45.627159</Y>
                <Z>-303.94641</Z>
            </BillPosition>
        </Billboard4>
        <Billboard5>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-158.28827</X>
                <Y>25.980392</Y>
                <Z>-436.67102</Z>
            </BillPosition>
        </Billboard5>
        <Billboard6>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-70.84021</X>
                <Y>29.296932</Y>
                <Z>-336.85901</Z>
            </BillPosition>
        </Billboard6>
        <Billboard7>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-145.33524</X>
                <Y>34.715897</Y>
                <Z>-300.1676</Z>
            </BillPosition>
        </Billboard7>
        <Billboard8>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-214.62643</X>
                <Y>47.691986</Y>
                <Z>-294.01776</Z>
            </BillPosition>
        </Billboard8>
        <Billboard9>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-226.96954</X>
                <Y>49.423241</Y>
                <Z>-269.39203</Z>
            </BillPosition>
        </Billboard9>
        <Billboard10>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-146.47226</X>
                <Y>38.373123</Y>
                <Z>-305.90948</Z>
            </BillPosition>
        </Billboard10>
        <Billboard11>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-112.29288</X>
                <Y>28.647421</Y>
                <Z>-336.57336</Z>
            </BillPosition>
        </Billboard11>
        <Billboard12>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-215.45712</X>
                <Y>36.795734</Y>
                <Z>-260.13544</Z>
            </BillPosition>
        </Billboard12>
        <Billboard13>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-282.04385</X>
                <Y>34.674095</Y>
                <Z>-276.12866</Z>
            </BillPosition>
        </Billboard13>
        <Billboard14>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-164.82166</X>
                <Y>36.675659</Y>
                <Z>-293.84082</Z>
            </BillPosition>
        </Billboard14>
        <Billboard15>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-135.94968</X>
                <Y>25.980392</Y>
                <Z>-247.81201</Z>
            </BillPosition>
        </Billboard15>
        <Billboard16>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-179.5383</X>
                <Y>36.37159</Y>
                <Z>-255.18835</Z>
            </BillPosition>
        </Billboard16>
        <Billboard17>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-180.43912</X>
                <Y>35.871914</Y>
                <Z>-252.54663</Z>
            </BillPosition>
        </Billboard17>
        <Billboard18>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-135.52438</X>
                <Y>25.980392</Y>
                <Z>-266.3902</Z>
            </BillPosition>
        </Billboard18>
        <Billboard19>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-125.935</X>
                <Y>29.615438</Y>
                <Z>-297.84595</Z>
            </BillPosition>
        </Billboard19>
        <Billboard20>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-206.55988</X>
                <Y>27.797405</Y>
                <Z>-229.4101</Z>
            </BillPosition>
        </Billboard20>
        <Billboard21>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-253.38684</X>
                <Y>27.28764</Y>
                <Z>-223.84082</Z>
            </BillPosition>
        </Billboard21>
        <Billboard22>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-119.23679</X>
                <Y>29.543722</Y>
                <Z>-279.51361</Z>
            </BillPosition>
        </Billboard22>
        <Billboard23>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-82.666718</X>
                <Y>27.19207</Y>
                <Z>-285.32056</Z>
            </BillPosition>
        </Billboard23>
        <Billboard24>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-159.43707</X>
                <Y>25.784313</Y>
                <Z>-240.73914</Z>
            </BillPosition>
        </Billboard24>
        <Billboard25>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-193.60818</X>
                <Y>29.626381</Y>
                <Z>-203.53119</Z>
            </BillPosition>
        </Billboard25>
        <Billboard26>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-93.222412</X>
                <Y>31.306879</Y>
                <Z>-243.97003</Z>
            </BillPosition>
        </Billboard26>
        <Billboard27>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-93.523315</X>
                <Y>30.796852</Y>
                <Z>-239.68701</Z>
            </BillPosition>
        </Billboard27>
        <Billboard28>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-121.87549</X>
                <Y>26.937614</Y>
                <Z>-243.76685</Z>
            </BillPosition>
        </Billboard28>
        <Billboard29>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-173.88861</X>
                <Y>26.001507</Y>
                <Z>-230.8252</Z>
            </BillPosition>
        </Billboard29>
        <Billboard30>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-97.869781</X>
                <Y>38.596115</Y>
                <Z>-188.37134</Z>
            </BillPosition>
        </Billboard30>
        <Billboard31>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-77.362122</X>
                <Y>42.302521</Y>
                <Z>-165.07001</Z>
            </BillPosition>
        </Billboard31>
        <Billboard32>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-122.8623</X>
                <Y>38.631691</Y>
                <Z>-177.23956</Z>
            </BillPosition>
        </Billboard32>
        <Billboard33>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-179.76218</X>
                <Y>27.760893</Y>
                <Z>-201.55658</Z>
            </BillPosition>
        </Billboard33>
        <Billboard34>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-72.722839</X>
                <Y>32.84314</Y>
                <Z>-251.0647</Z>
            </BillPosition>
        </Billboard34>
        <Billboard35>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-9.1290588</X>
                <Y>27.827328</Y>
                <Z>-273.84467</Z>
            </BillPosition>
        </Billboard35>
        <Billboard36>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-38.587891</X>
                <Y>30.024326</Y>
                <Z>-366.52399</Z>
            </BillPosition>
        </Billboard36>
        <Billboard37>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-71.563019</X>
                <Y>27.719601</Y>
                <Z>-328.09015</Z>
            </BillPosition>
        </Billboard37>
        <Billboard38>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-34.20639</X>
                <Y>33.679573</Y>
                <Z>-210.53632</Z>
            </BillPosition>
        </Billboard38>
        <Billboard39>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-50.59024</X>
                <Y>35.444908</Y>
                <Z>-200.1203</Z>
            </BillPosition>
        </Billboard39>
        <Billboard40>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-63.384247</X>
                <Y>45.481396</Y>
                <Z>-168.72125</Z>
            </BillPosition>
        </Billboard40>
        <Billboard41>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-34.705658</X>
                <Y>35.63707</Y>
                <Z>-163.55145</Z>
            </BillPosition>
        </Billboard41>
        <Billboard42>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-201.0672</X>
                <Y>53.892925</Y>
                <Z>-310.49426</Z>
            </BillPosition>
        </Billboard42>
        <Billboard43>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-216.20529</X>
                <Y>47.740112</Y>
                <Z>-289.86505</Z>
            </BillPosition>
        </Billboard43>
        <Billboard44>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-187.82919</X>
                <Y>39.128548</Y>
                <Z>-298.77869</Z>
            </BillPosition>
        </Billboard44>
        <Billboard45>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-164.46365</X>
                <Y>26.797186</Y>
                <Z>-267.33032</Z>
            </BillPosition>
        </Billboard45>
        <Billboard46>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-219.62436</X>
                <Y>48.720615</Y>
                <Z>-279.95532</Z>
            </BillPosition>
        </Billboard46>
        <Billboard47>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-185.23459</X>
                <Y>42.705585</Y>
                <Z>-303.09167</Z>
            </BillPosition>
        </Billboard47>
        <Billboard48>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-133.70645</X>
                <Y>37.507389</Y>
                <Z>-341.4328</Z>
            </BillPosition>
        </Billboard48>
        <Billboard49>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-146.16367</X>
                <Y>45.603298</Y>
                <Z>-316.19995</Z>
            </BillPosition>
        </Billboard49>
        <Billboard50>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-211.5166</X>
                <Y>41.106857</Y>
                <Z>-275.69061</Z>
            </BillPosition>
        </Billboard50>
        <Billboard51>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-239.79114</X>
                <Y>41.642502</Y>
                <Z>-259.28253</Z>
            </BillPosition>
        </Billboard51>
        <Billboard52>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-165.81833</X>
                <Y>37.870781</Y>
                <Z>-295.78021</Z>
            </BillPosition>
        </Billboard52>
        <Billboard53>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-176.42203</X>
                <Y>25.980392</Y>
                <Z>-502.04578</Z>
            </BillPosition>
        </Billboard53>
        <Billboard54>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-173.17166</X>
                <Y>42.0336</Y>
                <Z>-300.44452</Z>
            </BillPosition>
        </Billboard54>
        <Billboard55>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-229.69873</X>
                <Y>40.182648</Y>
                <Z>-258.07428</Z>
            </BillPosition>
        </Billboard55>
        <Billboard56>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-163.211</X>
                <Y>25.980392</Y>
                <Z>-507.19122</Z>
            </BillPosition>
        </Billboard56>
        <Billboard57>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-142.22852</X>
                <Y>25.980392</Y>
                <Z>-511.0329</Z>
            </BillPosition>
        </Billboard57>
        <Billboard58>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-179.89938</X>
                <Y>45.273766</Y>
                <Z>-304.44415</Z>
            </BillPosition>
        </Billboard58>
        <Billboard59>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-141.27795</X>
                <Y>42.753788</Y>
                <Z>-337.35126</Z>
            </BillPosition>
        </Billboard59>
        <Billboard60>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-151.89865</X>
                <Y>44.374641</Y>
                <Z>-306.99438</Z>
            </BillPosition>
        </Billboard60>
        <Billboard61>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-495.03778</X>
                <Y>25.980392</Y>
                <Z>-466.77875</Z>
            </BillPosition>
        </Billboard61>
        <Billboard62>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-131.78833</X>
                <Y>25.980392</Y>
                <Z>-511.13501</Z>
            </BillPosition>
        </Billboard62>
        <Billboard63>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-190.77582</X>
                <Y>25.980392</Y>
                <Z>-508.14734</Z>
            </BillPosition>
        </Billboard63>
        <Billboard64>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-101.68298</X>
                <Y>40.476814</Y>
                <Z>-172.37592</Z>
            </BillPosition>
        </Billboard64>
        <Billboard65>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-155.42703</X>
                <Y>30.506496</Y>
                <Z>-190.27802</Z>
            </BillPosition>
        </Billboard65>
        <Billboard66>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-58.956207</X>
                <Y>43.442131</Y>
                <Z>-159.85986</Z>
            </BillPosition>
        </Billboard66>
        <Billboard67>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-55.68869</X>
                <Y>29.762993</Y>
                <Z>-343.16443</Z>
            </BillPosition>
        </Billboard67>
        <Billboard68>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-18.502838</X>
                <Y>26.176758</Y>
                <Z>-352.34875</Z>
            </BillPosition>
        </Billboard68>
        <Billboard69>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-68.322968</X>
                <Y>26.176758</Y>
                <Z>-315.75885</Z>
            </BillPosition>
        </Billboard69>
        <Billboard70>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-119.14645</X>
                <Y>32.999199</Y>
                <Z>-350.33008</Z>
            </BillPosition>
        </Billboard70>
        <Billboard71>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-84.544769</X>
                <Y>26.414888</Y>
                <Z>-327.12817</Z>
            </BillPosition>
        </Billboard71>
        <Billboard72>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-446.63586</X>
                <Y>25.980469</Y>
                <Z>-456.23346</Z>
            </BillPosition>
        </Billboard72>
        <Billboard73>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-476.3251</X>
                <Y>25.980469</Y>
                <Z>-451.81744</Z>
            </BillPosition>
        </Billboard73>
        <Billboard74>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-358.13623</X>
                <Y>25.980469</Y>
                <Z>-421.36084</Z>
            </BillPosition>
        </Billboard74>
        <Billboard75>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-401.32062</X>
                <Y>25.980469</Y>
                <Z>-362.12347</Z>
            </BillPosition>
        </Billboard75>
        <Billboard76>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-387.15979</X>
                <Y>45.515743</Y>
                <Z>-291.44684</Z>
            </BillPosition>
        </Billboard76>
        <Billboard77>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-378.00723</X>
                <Y>49.067326</Y>
                <Z>-263.90338</Z>
            </BillPosition>
        </Billboard77>
        <Billboard78>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-374.4483</X>
                <Y>42.877838</Y>
                <Z>-272.23352</Z>
            </BillPosition>
        </Billboard78>
        <Billboard79>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-370.70309</X>
                <Y>31.851864</Y>
                <Z>-313.01135</Z>
            </BillPosition>
        </Billboard79>
        <Billboard80>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-318.55823</X>
                <Y>29.273998</Y>
                <Z>-292.19122</Z>
            </BillPosition>
        </Billboard80>
        <Billboard81>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-348.16534</X>
                <Y>32.210159</Y>
                <Z>-250.56268</Z>
            </BillPosition>
        </Billboard81>
        <Billboard82>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-359.55176</X>
                <Y>37.662987</Y>
                <Z>-225.43085</Z>
            </BillPosition>
        </Billboard82>
        <Billboard83>
            <BillboardType>1</BillboardType>
            <TextureNum>6</TextureNum>
            <BillSize>
                <X>18.5</X>
                <Y>50</Y>
            </BillSize>
            <BillPosition>
                <X>-302.24039</X>
                <Y>33.988045</Y>
                <Z>-252.57483</Z>
            </BillPosition>
        </Billboard83>
    </BillboardDesc>
</TerrainDesc>
